src/objects/Class__c.object
<CustomObject>
    <fields>
        <fullName>ClassSubject__c</fullName>
        <label>Class Subject</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CPS</fullName>
                </value>
                <value>
                    <fullName>English</fullName>
                </value>
                <value>
                    <fullName>History</fullName>
                </value>
                <value>
                    <fullName>Math</fullName>
                </value>
                <value>
                    <fullName>Science</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ClassTopic__c</fullName>
        <label>Class Topic</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>ClassSubject__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>ClassTopic</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ClassEnrollment__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Class Enrollments</relationshipLabel>
        <relationshipName>ClassEnrollments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Class Enrollments</relationshipLabel>
        <relationshipName>ClassEnrollments</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Class Enrollment</label>
    <nameField>
        <displayFormat>CE-{0000}</displayFormat>
        <label>Class Enrollment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Class Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Age__c</fullName>
        <inlineHelpText>Enter the age of the student.</inlineHelpText>
        <label>Age</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <caseSensitive>true</caseSensitive>
        <inlineHelpText>name@email.com</inlineHelpText>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Enrolled</fullName>
                </value>
                <value>
                    <fullName>Graduated</fullName>
                </value>
                <value>
                    <fullName>Prospective</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
                <value>
                    <fullName>Expelled</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/DMLExamples.cls
public class DMLExamples {
    
    public static void classExample() {
        // Class
        Class__c c = new Class__c();
        c.Name = 'HIS400';
        c.ClassSubject__c = 'History';
        c.ClassTopic__c = 'American History';
        c.StartDate__c = Date.newInstance(2019, 7, 30);
        c.EndDate__c = Date.newInstance(2019, 8, 2);
        insert c;
        
        // Student
        Student__c s = new Student__c();
        s.Name = 'Laura';
        s.Age__c = 22;
        s.Email__c = 'Laura@gmail.com';
        s.Status__c = 'Graduated';
        insert s;

		// Class Enrollment
		ClassEnrollment__c ce = new ClassEnrollment__c(Class__c=c.Id, Student__c=s.Id);
        insert new ClassEnrollment__c(Class__c=c.Id, Student__c=s.Id);
    }
    
    // We DO NOT want to perform DML operations  on individual records.
    public static void dontDoThis() {
        Account a = new Account(Name='test1');
        insert a;
        Account a2 = new Account(Name='test2');
        insert a2;
        Account a3 = new Account(Name='test3');
        insert a3;
    }
    
    // Instead, perform DML on a list of records
    public static void doThis() {
        List<Account> accList = new List<Account>();
        
        for(Integer i = 0; i < 3; i++) {
            accList.add(new Account(Name='t'+i));
        }
        insert accList;
    }
    
    /* Using the upsert operation, you can either update or insert an existing record
     * in one call. To determine wherter a record already exists, the upsert statement
     * uses the record's ID as the key to match the records.
     * 
     * - If the key is not matched, then a new record is created.
     * - If the key is matched once, then the existinf record is updated.
     * - Id using the external ID, if the key is matched multiple times. then an error
     *   is generated and the record is neither updated or inserted
    */
    public static void upsertExample() {
        List<Account> accList = [Select BillingCity From Account Where BillingCity='New York'];
        
        for(Account a: accList) {
            a.BillingCity = 'Mumbai';
        }
        
        accList.add(new Account(Name='Acme', BillingCity='San Francisco'));
        
        // 	Invalid record (if this is in which does not work the entire thing would not be inserted or work)
        // accList.add(new Account(BillingCity='San Francisco'));
        
        upsert accList;
    }
    
    /* Deleted records are not deleted permanently from the SF, bu are inserted
     * into the Recylce Bin for 15 dates where they can be restored
    */
    public static void deleteExample() {
       // insert new Account(Name='BobBill\'s Antique Shop');
       Account a1 = new Account(Name='BobBill\'s Antique Shop');
       insert a1;
       // Account a = [SELECT Name FROM Account Where Name='BobBill\'s Antique Shop'];
        
        System.debug('a: ' + a1);
        delete a1;
        
        List<Account> acs = [SELECT Name FROM Account Where Name='BobBill\'s Antique Shop' LIMIT 1];
        System.debug('acs: ' + acs);
    }
    
    /* SOQL statements can use the ALL ROWS keywords/clause to query all records in an org,
     * included deleted records.
    */
    public static void undeleteExample() {
        System.debug('Find Kelly from existing records ' + [SELECT Name FROM Student__c WHERE Name = 'Jimmy']);
        
        List<Student__c> students = [SELECT Name FROM Student__c WHERE Name = 'Jimmy' ALL ROWS];
        System.debug('Students - including deleted' + students);
        undelete students;
    }

}